# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mailServer
import re

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1291, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.whoIAm = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.whoIAm.setGeometry(QtCore.QRect(10, 10, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.whoIAm.setFont(font)
        self.whoIAm.setObjectName("whoIAm")
        self.themeCont = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.themeCont.setGeometry(QtCore.QRect(10, 60, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.themeCont.setFont(font)
        self.themeCont.setObjectName("themeCont")
        self.bodyCont = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.bodyCont.setGeometry(QtCore.QRect(10, 110, 591, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bodyCont.setFont(font)
        self.bodyCont.setObjectName("bodyCont")
        self.Send = QtWidgets.QPushButton(self.centralwidget)
        self.Send.setGeometry(QtCore.QRect(240, 450, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Send.setFont(font)
        self.Send.setObjectName("Send")
        self.ViewMails = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ViewMails.setGeometry(QtCore.QRect(620, 10, 661, 411))
        self.ViewMails.setObjectName("ViewMails")
        self.loadMails = QtWidgets.QPushButton(self.centralwidget)
        self.loadMails.setGeometry(QtCore.QRect(620, 450, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadMails.setFont(font)
        self.loadMails.setObjectName("loadMails")
        self.NextMail = QtWidgets.QPushButton(self.centralwidget)
        self.NextMail.setGeometry(QtCore.QRect(1150, 450, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NextMail.setFont(font)
        self.NextMail.setObjectName("NextMail")
        self.BackMail = QtWidgets.QPushButton(self.centralwidget)
        self.BackMail.setGeometry(QtCore.QRect(1000, 450, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BackMail.setFont(font)
        self.BackMail.setObjectName("BackMail")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.current_pos = 0
        self.list_of_emails = []

        self.Send.clicked.connect(self.sendMessage)
        self.loadMails.clicked.connect(self.loadEmail)
        self.BackMail.clicked.connect(self.pastEmail)
        self.NextMail.clicked.connect(self.nextEmail)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.whoIAm.setPlaceholderText(_translate("MainWindow", "Кому"))
        self.themeCont.setPlaceholderText(_translate("MainWindow", "Тема"))
        self.bodyCont.setPlaceholderText(_translate("MainWindow", "Содержание"))
        self.Send.setText(_translate("MainWindow", "Отправить"))
        self.loadMails.setText(_translate("MainWindow", "Загрузить почту"))
        self.NextMail.setText(_translate("MainWindow", "Следующее"))
        self.BackMail.setText(_translate("MainWindow", "Предыдущее"))

    def sendMessage(self):
        messageTo = self.whoIAm.toPlainText()
        theme = self.themeCont.toPlainText()
        body = self.bodyCont.toPlainText()
        if not re.match(r"[^@]+@[^@]+\.[^@]+", messageTo):
            print("Неправильный формат email-адреса")
        else:
            mailServer.sendMessage(messageTo,theme,body)

    def loadEmail(self):
        self.list_of_emails = mailServer.takeMessages()
        self.ViewMails.setPlainText(f'From: {self.list_of_emails[0][0]} \n\nSubject: {self.list_of_emails[0][1]} \n\nBody: {self.list_of_emails[0][2]}')

    def nextEmail(self):
        if self.current_pos == len(self.list_of_emails)-1:
            self.current_pos = 0
        else:
            self.current_pos +=1
        self.ViewMails.setPlainText(f'From: {self.list_of_emails[self.current_pos][0]} \n\nSubject: {self.list_of_emails[self.current_pos][1]} \n\nBody: {self.list_of_emails[self.current_pos][2]}')

    def pastEmail(self):
        if self.current_pos == 0:
            self.current_pos = len(self.list_of_emails)-1
        else:
            self.current_pos -= 1
        self.ViewMails.setPlainText(
            f'From: {self.list_of_emails[self.current_pos][0]} \n\nSubject: {self.list_of_emails[self.current_pos][1]} \n\nBody: {self.list_of_emails[self.current_pos][2]}')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
