# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cezar_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import cezar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 745)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputMessage = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputMessage.setGeometry(QtCore.QRect(10, 10, 821, 331))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inputMessage.setFont(font)
        self.inputMessage.setObjectName("inputMessage")
        self.outputMessage = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.outputMessage.setGeometry(QtCore.QRect(10, 410, 821, 331))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.outputMessage.setFont(font)
        self.outputMessage.setReadOnly(True)
        self.outputMessage.setObjectName("outputMessage")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(390, 370, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.secondKey = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.secondKey.setGeometry(QtCore.QRect(840, 640, 311, 101))
        self.secondKey.setObjectName("secondKey")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 364, 91, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(960, 600, 151, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.encypt_bt = QtWidgets.QPushButton(self.centralwidget)
        self.encypt_bt.setGeometry(QtCore.QRect(840, 10, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.encypt_bt.setFont(font)
        self.encypt_bt.setObjectName("encypt_bt")
        self.decrypt_bt = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt_bt.setGeometry(QtCore.QRect(1000, 10, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.decrypt_bt.setFont(font)
        self.decrypt_bt.setObjectName("decrypt_bt")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.encypt_bt.clicked.connect(lambda : self.encode(1))
        self.decrypt_bt.clicked.connect(lambda: self.encode(-1))

        self.encoded = cezar.Cezar()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputMessage.setPlaceholderText(_translate("MainWindow", "Enter the message here"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox.setItemText(24, _translate("MainWindow", "25"))
        self.label.setText(_translate("MainWindow", "First key"))
        self.label_2.setText(_translate("MainWindow", "Second key"))
        self.encypt_bt.setText(_translate("MainWindow", "Encrypt"))
        self.decrypt_bt.setText(_translate("MainWindow", "Decrypt"))


    def encode(self,mode):
        message = self.inputMessage.toPlainText()
        key1 = int(self.comboBox.currentText())
        key2 = self.secondKey.toPlainText()
        response = self.encoded.encrypt_message(message,key1,mode,key2)
        if not response["response"]["process"]:
            self.error_screen(response["response"]["error"])
        else:
            self.outputMessage.setPlainText(response["context"])



    def error_screen(self,error_message):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.setWindowTitle("Incorrect Data")
        msg.setText(error_message)

        x = msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
