# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import main
import cezar

class Ui_MainWindow(object):

    def __init__(self):
        self.app = QtWidgets.QApplication(sys.argv)
        self.MainWindow = QtWidgets.QMainWindow()


    def back_button(self):
        self.ui = main.Ui_MainWindow()
        self.ui.setupUi(self.ui.MainWindow)
        self.MainWindow.hide()
        self.ui.MainWindow.show()


    def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(993, 600)
            MainWindow.setStyleSheet(
                "background-color: qlineargradient(spread:reflect, x1:0.29, y1:1, x2:0.301, y2:0.517045, stop:0 rgba(33, 100, 142, 255), stop:1 rgba(131, 229, 255, 255));")
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.TextInput = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.TextInput.setGeometry(QtCore.QRect(10, 10, 971, 251))
            font = QtGui.QFont()
            font.setPointSize(15)
            self.TextInput.setFont(font)
            self.TextInput.setStyleSheet("background-color: rgb(20, 78, 91);\n"
                                         "color: rgb(255, 255, 255);")
            self.TextInput.setObjectName("TextInput")
            self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
            self.lcdNumber.setGeometry(QtCore.QRect(10, 290, 64, 23))
            self.lcdNumber.setStyleSheet("background-color: rgb(90, 158, 171);")
            self.lcdNumber.setObjectName("lcdNumber")
            self.TextOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.TextOutput.setGeometry(QtCore.QRect(10, 340, 971, 251))
            font = QtGui.QFont()
            font.setPointSize(15)
            self.TextOutput.setFont(font)
            self.TextOutput.setStyleSheet("background-color: rgb(20, 78, 91);\n"
                                          "color: rgb(255, 255, 255);")
            self.TextOutput.setReadOnly(True)
            self.TextOutput.setObjectName("TextOutput")
            self.Back = QtWidgets.QPushButton(self.centralwidget)
            self.Back.setGeometry(QtCore.QRect(870, 270, 111, 61))
            font = QtGui.QFont()
            font.setPointSize(13)
            self.Back.setFont(font)
            self.Back.setStyleSheet("QPushButton {\n"
                                    "background-color: rgb(90, 158, 171);\n"
                                    "border-radius: 25px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:enabled{\n"
                                    "background-color: rgb(90, 158, 171);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover{\n"
                                    "background-color: rgb(60, 128, 141);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed{\n"
                                    "background-color: rgb(50, 118, 131);\n"
                                    "}")
            self.Back.setObjectName("Back")
            self.StartEncrypt = QtWidgets.QPushButton(self.centralwidget)
            self.StartEncrypt.setGeometry(QtCore.QRect(100, 270, 131, 61))
            font = QtGui.QFont()
            font.setPointSize(11)
            self.StartEncrypt.setFont(font)
            self.StartEncrypt.setStyleSheet("QPushButton {\n"
                                            "background-color: rgb(90, 158, 171);\n"
                                            "border-radius: 25px;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:enabled{\n"
                                            "background-color: rgb(90, 158, 171);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover{\n"
                                            "background-color: rgb(60, 128, 141);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed{\n"
                                            "background-color: rgb(50, 118, 131);\n"
                                            "}")
            self.StartEncrypt.setObjectName("StartEncrypt")
            self.comboBox = QtWidgets.QComboBox(self.centralwidget)
            self.comboBox.setGeometry(QtCore.QRect(290, 290, 69, 22))
            font = QtGui.QFont()
            font.setPointSize(15)
            self.comboBox.setFont(font)
            self.comboBox.setStyleSheet("background-color: rgb(90, 158, 171);")
            self.comboBox.setObjectName("comboBox")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.StartDecrypt = QtWidgets.QPushButton(self.centralwidget)
            self.StartDecrypt.setGeometry(QtCore.QRect(720, 270, 131, 61))
            font = QtGui.QFont()
            font.setPointSize(11)
            self.StartDecrypt.setFont(font)
            self.StartDecrypt.setStyleSheet("QPushButton {\n"
                                            "background-color: rgb(90, 158, 171);\n"
                                            "border-radius: 25px;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:enabled{\n"
                                            "background-color: rgb(90, 158, 171);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover{\n"
                                            "background-color: rgb(60, 128, 141);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed{\n"
                                            "background-color: rgb(50, 118, 131);\n"
                                            "}")
            self.StartDecrypt.setObjectName("StartDecrypt")
            self.Key2 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.Key2.setGeometry(QtCore.QRect(390, 270, 301, 61))
            font = QtGui.QFont()
            font.setPointSize(15)
            self.Key2.setFont(font)
            self.Key2.setStyleSheet("background-color: rgb(20, 78, 91);\n"
                                    "color: rgb(255, 255, 255);")
            self.Key2.setPlainText("")
            self.Key2.setObjectName("Key2")
            MainWindow.setCentralWidget(self.centralwidget)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TextInput.setPlaceholderText(_translate("MainWindow", "Write a message here"))
        self.Back.setText(_translate("MainWindow", "Back"))
        self.StartEncrypt.setText(_translate("MainWindow", "Encrypt message"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox.setItemText(24, _translate("MainWindow", "25"))
        self.StartDecrypt.setText(_translate("MainWindow", "Decrypt message"))
        self.Key2.setPlaceholderText(_translate("MainWindow", "Write a key here"))


        self.Back.clicked.connect(self.back_button)
        self.StartEncrypt.clicked.connect(lambda : self.start(1))
        self.StartDecrypt.clicked.connect(lambda : self.start(-1))


    def start(self,mode):
        key = int(self.comboBox.currentText())
        key2 = self.Key2.toPlainText()
        message = self.TextInput.toPlainText()
        tmp = cezar.Cezar()
        response = tmp.encrypt_message(message,key,mode,key2)
        if response["response"]["process"] == False:
            self.error_screen(response["response"]["error"])
        else:
            self.TextOutput.setPlainText(response["context"])
            self.TextInput.setPlainText(message.upper().replace(" ",""))

            self.lcdNumber.display(response["time"])


    def error_screen(self,error_message):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Incorrect Input")
        msg.setText(error_message)
        msg.setIcon(QtWidgets.QMessageBox.Critical)

        x = msg.exec_()