# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import encrypt

class Ui_MainWindow(object):


    def __init__(self):
        self.app = QtWidgets.QApplication(sys.argv)
        self.MainWindow = QtWidgets.QMainWindow()


    def encrypt_window(self):
        self.ui = encrypt.Ui_MainWindow()
        self.ui.setupUi(self.ui.MainWindow)
        self.MainWindow.hide()
        self.ui.MainWindow.show()


    def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(827, 454)
            MainWindow.setStyleSheet(
                "background-color: qlineargradient(spread:reflect, x1:0.29, y1:1, x2:0.301, y2:0.517045, stop:0 rgba(33, 100, 142, 255), stop:1 rgba(131, 229, 255, 255));")
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.encrypt = QtWidgets.QPushButton(self.centralwidget)
            self.encrypt.setGeometry(QtCore.QRect(300, 220, 231, 101))
            font = QtGui.QFont()
            font.setFamily("Palatino Linotype")
            font.setPointSize(30)
            font.setBold(True)
            font.setWeight(75)
            self.encrypt.setFont(font)
            self.encrypt.setStyleSheet("QPushButton {\n"
                                       "background-color: rgb(90, 158, 171);\n"
                                       "border-radius: 35px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:enabled{\n"
                                       "background-color: rgb(90, 158, 171);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover{\n"
                                       "background-color: rgb(60, 128, 141);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "background-color: rgb(50, 118, 131);\n"
                                       "}")
            self.encrypt.setObjectName("encrypt")
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setEnabled(True)
            self.label.setGeometry(QtCore.QRect(70, 60, 711, 91))
            font = QtGui.QFont()
            font.setFamily("Palatino Linotype")
            font.setPointSize(60)
            self.label.setFont(font)
            self.label.setStyleSheet("background-color: rgb(73, 240, 255,0);")
            self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
            self.label.setObjectName("label")
            self.label_2 = QtWidgets.QLabel(self.centralwidget)
            self.label_2.setGeometry(QtCore.QRect(10, 420, 81, 31))
            font = QtGui.QFont()
            font.setPointSize(15)
            font.setBold(True)
            font.setWeight(75)
            self.label_2.setFont(font)
            self.label_2.setStyleSheet("background-color: rgb(73, 255, 255,0);")
            self.label_2.setObjectName("label_2")
            self.label_3 = QtWidgets.QLabel(self.centralwidget)
            self.label_3.setGeometry(QtCore.QRect(650, 420, 171, 31))
            font = QtGui.QFont()
            font.setPointSize(13)
            font.setBold(True)
            font.setWeight(75)
            self.label_3.setFont(font)
            self.label_3.setStyleSheet("background-color: rgb(64, 246, 255,0);")
            self.label_3.setObjectName("label_3")
            MainWindow.setCentralWidget(self.centralwidget)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

            self.encrypt.clicked.connect(self.encrypt_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encrypt.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Gaius Iulius Caesar"))
        self.label_2.setText(_translate("MainWindow", "v1.0"))
        self.label_3.setText(_translate("MainWindow", "Created by drawdea"))



