# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OutputContainer = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.OutputContainer.setGeometry(QtCore.QRect(10, 300, 781, 291))
        self.OutputContainer.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.OutputContainer.setFont(font)
        self.OutputContainer.setObjectName("OutputContainer")
        self.GuidInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.GuidInput.setGeometry(QtCore.QRect(10, 10, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.GuidInput.setFont(font)
        self.GuidInput.setObjectName("GuidInput")
        self.GetButton = QtWidgets.QPushButton(self.centralwidget)
        self.GetButton.setGeometry(QtCore.QRect(10, 60, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.GetButton.setFont(font)
        self.GetButton.setObjectName("GetButton")
        self.PostButton = QtWidgets.QPushButton(self.centralwidget)
        self.PostButton.setGeometry(QtCore.QRect(10, 120, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PostButton.setFont(font)
        self.PostButton.setObjectName("PostButton")
        self.HeadButton = QtWidgets.QPushButton(self.centralwidget)
        self.HeadButton.setGeometry(QtCore.QRect(10, 180, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HeadButton.setFont(font)
        self.HeadButton.setObjectName("HeadButton")
        self.OptionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.OptionsButton.setGeometry(QtCore.QRect(10, 240, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.OptionsButton.setFont(font)
        self.OptionsButton.setObjectName("OptionsButton")
        self.UserNameInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.UserNameInput.setGeometry(QtCore.QRect(580, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserNameInput.setFont(font)
        self.UserNameInput.setObjectName("UserNameInput")
        self.PhoneInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PhoneInput.setGeometry(QtCore.QRect(580, 70, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PhoneInput.setFont(font)
        self.PhoneInput.setObjectName("PhoneInput")
        self.NameInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.NameInput.setGeometry(QtCore.QRect(580, 130, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NameInput.setFont(font)
        self.NameInput.setObjectName("NameInput")
        self.AddressInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.AddressInput.setGeometry(QtCore.QRect(580, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AddressInput.setFont(font)
        self.AddressInput.setObjectName("AddressInput")
        self.PassInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PassInput.setGeometry(QtCore.QRect(580, 250, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PassInput.setFont(font)
        self.PassInput.setObjectName("PassInput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.GetButton.clicked.connect(self.get_data)
        self.PostButton.clicked.connect(self.post_data)
        self.HeadButton.clicked.connect(self.get_head)
        self.OptionsButton.clicked.connect(self.get_options)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GuidInput.setPlaceholderText(_translate("MainWindow", "guid"))
        self.GetButton.setText(_translate("MainWindow", "Get"))
        self.PostButton.setText(_translate("MainWindow", "Post"))
        self.HeadButton.setText(_translate("MainWindow", "Head"))
        self.OptionsButton.setText(_translate("MainWindow", "Options"))
        self.UserNameInput.setPlaceholderText(_translate("MainWindow", "user name"))
        self.PhoneInput.setPlaceholderText(_translate("MainWindow", "phone"))
        self.NameInput.setPlaceholderText(_translate("MainWindow", "name"))
        self.AddressInput.setPlaceholderText(_translate("MainWindow", "address"))
        self.PassInput.setPlaceholderText(_translate("MainWindow", "pass id"))

    def get_data(self):
        guid = self.GuidInput.toPlainText()
        response = requests.get(f"http://localhost:5000/get_data_guid?guid={guid}")
        if not response.json()['process']:
            self.OutputContainer.setPlainText("This user doesn't exist")
        else:
            data = response.json()['content']
            self.OutputContainer.setPlainText(f'Name: {data["name"]}\n'
                                              f'User name: {data["nick_name"]}\n'
                                              f'Email: {data["email"]}\n'
                                              f'Address: {data["address"]}\n'
                                              f'Pass ID: {data["pass id"]}\n'
                                              f'Phone: {data["phone"]}\n')


    def post_data(self):
        guid = self.GuidInput.toPlainText()
        data = {
            "name": self.NameInput.toPlainText(),
            "userName": self.UserNameInput.toPlainText(),
            "address": self.AddressInput.toPlainText(),
            "phone" :self.PhoneInput.toPlainText(),
            "pass_id" : self.PassInput.toPlainText()
        }
        response = requests.post(f'http://localhost:5000/process_data?guid={guid}', json=data)
        if not response.json()['process']:
            self.OutputContainer.setPlainText("This user doesn't exist")
        else:
            self.OutputContainer.setPlainText("Data was changed")

    def get_head(self):
        response = requests.head('http://localhost:5000/get_head')
        self.OutputContainer.setPlainText(str(response)+' / '+str(response.headers.get('time')))


    def get_options(self):
        response = requests.options('http://localhost:5000/get_options')
        self.OutputContainer.setPlainText(str(response)+' '+str(response.headers.get('Access-Control-Allow-Methods')))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
